#ifndef __EXECTIME_HPP_INCLUDED__
#define __EXECTIME_HPP_INCLUDED__

#define PROGRAM_NAME "exectime"
#define PROGRAM_VERSION_MAJOR "0"
#define PROGRAM_VERSION_MINOR "0"
#define PROGRAM_VERSION_BUILD "3"
#define PROGRAM_VERSION PROGRAM_VERSION_MAJOR "." PROGRAM_VERSION_MINOR "." PROGRAM_VERSION_BUILD
#define PROGRAM_YEAR "2016"
#define PROGRAM_LICENSE "GPLv3"

#endif //__EXECTIME_HPP_INCLUDED__
